(clear)
(load "clases.clp")
(load "instancias/epocas.clp")
(load "instancias/temas.clp")
(load "instancias/generos.clp")
(load "instancias/idiomas.clp")
(load "instancias/instancias.clp")
(load "main.clp")
(reset)
(run)
